name: Mirror Repositories

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-email@example.com'

      - name: Mirror repositories
        env:
          DEV_ACCOUNT: developer-username
          PROF_ACCOUNT: professional-username
          PROFESSIONAL_TOKEN: ${{ secrets.PROFESSIONAL_TOKEN }}
        run: |
          REPOS=("repo1" "repo2" "repo3")
          for REPO in "${REPOS[@]}"
          do
            git clone --mirror https://github.com/$DEV_ACCOUNT/$REPO.git
            cd $REPO.git
            git remote add professional https://professional-username:${{ secrets.PROFESSIONAL_TOKEN }}@github.com/$PROF_ACCOUNT/$REPO.git
            git push --mirror professional
            cd ..
            rm -rf $REPO.git
          done
